title: ACA Books
tagline: York Radical Library
# email:
description: York Radical Library
instagram: aca.books
# twitter:
# facebook:
# telegram:

url: joe.irving.me.uk
repository: joe-irving/acabooks
permalink: pretty

collections:
  books:
    output: true
    permalink: /:collection/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

locale: en_GB
