title: ACABooks
# email:
# description:
url: joe.irving.me.uk
baseurl: '/acabooks'
repository: joe-irving/acabooks


permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

instagram: aca.books
# twitter:
# facebook:
