title: ACA Books
tagline: York Radical Library
description: York Radical Library
instagram: aca.books
# email:
# twitter:
# facebook:
# telegram:

url: http://acabooks.org.uk
repository: joe-irving/acabooks
permalink: /:categories/:year/:title/

collections:
  books:
    output: true
    permalink: /:collection/:title
  posts:
    permalink: /blog/:year/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

locale: en_GB
defaults:
- scope:
    path: ''
  values:
    image: "/uploads/acabooksall.png"
