---
title: ACA Books
tagline: York's Radical Library
description: "Anarcho Cosmic Activist Books, created in April 2021,\nis York’s new
  radical library: a grass-roots group sharing knowledge and ideas\nthrough books. "
instagram: aca.books
email: acabooksyork@gmail.com
twitter: ''
facebook: ''
telegram: ''
url: https://acabooks.org.uk
repository: joe-irving/acabooks
permalink: "/:categories/:year/:title/"
theme: minima
collections:
  books:
    output: true
    permalink: "/:collection/:title"
  posts:
    permalink: "/blog/:year/:title"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-paginate-v2
pagination:
  enabled: true
  permalink: /:num/
  per_page: 10
  collection: books
csv:
  books:
    source: https://docs.google.com/spreadsheets/d/1ZwmcMVbU6dLMX06iufNnOLyNSGpZdLrsDbzNtnnaUVY/gviz/tq?tqx=out:csv&sheet=Books

autopages:
  enabled: true
  tags:
    layouts:
      - books-page.html
    title: ':tag'
  collections:
    enabled: false
  categories:
    enabled: false
socials:
  name: ACA Books
  links:
  - https://www.instagram.com/aca.books/
locale: en_GB
defaults:
- scope:
    path: ''
  values:
    image: "/uploads/acabooksall.png"
