title: ACA Books
# email:
description: York Radial Library
instagram: aca.books
# twitter:
# facebook:
# telegram:

url: joe.irving.me.uk
baseurl: '/acabooks'
repository: joe-irving/acabooks
permalink: pretty

collections:
  books:
    output: true
    permalink: /:collection/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
