---
title: ACA Books
tagline: York's Radical Library
description: "Anarcho Cosmic Activist Books, created in April 2021,\nis York’s new
  radical library: grass-roots group sharing knowledge and ideas\nthrough books. "
instagram: aca.books
url: http://acabooks.org.uk
repository: joe-irving/acabooks
permalink: "/:categories/:year/:title/"
collections:
  books:
    output: true
    permalink: "/:collection/:title"
  posts:
    permalink: "/blog/:year/:title"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
socials:
  name: ACA Books
  links:
  - https://www.instagram.com/aca.books/
locale: en_GB
defaults:
- scope:
    path: ''
  values:
    image: "/uploads/acabooksall.png"
