title: ACA Books
tagline: York Radical Library
description: |-
  York’s New Radical Library, created in April 2021,
  is a grass-roots group sharing knowledge and ideas
  through books.
instagram: aca.books
# email: acabooks@bicycle.ga
# twitter:
# facebook:
# telegram:

url: http://acabooks.org.uk
repository: joe-irving/acabooks
permalink: /:categories/:year/:title/

collections:
  books:
    output: true
    permalink: /:collection/:title
  posts:
    permalink: /blog/:year/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

socials:
  name: ACA Books
  links:
    - https://www.instagram.com/aca.books/

locale: en_GB
defaults:
- scope:
    path: ''
  values:
    image: "/uploads/acabooksall.png"
